name : muhamad fatkhur rizki
author : muhamad fatkhur rizki
email: rizkijack99mmm@gmail.com
facebook_username: rizkirosoneri
github_username: mfrizki
twitter_username: 
tiktok_username: mf.rizki
youtube_username: UCkvyvWEOcjzdrlcfWSinQyQ
linkedin_username: 
instagram_username:
theme: jekyll-theme-merlot
